version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bisbis10
      POSTGRES_PASSWORD: bisbis10
      POSTGRES_DB: bisbis10
   # volumes:
    #  - ./data:/var/lib/postgresql/data --> in case u need to save data to local storage
    ports:
      - "5432:5432"